import imported from './generated/imported.json';import type{IndicatorSuggestion,Project}from'./types';
export const strategy={mission:'Tecnologia e inovação a serviço do cidadão para simplificar, promover e cuidar.',vision:'Universalizar o acesso aos serviços públicos no Recife orientados ao zero clique.',values:'Cidadãocentrismo; inteligência coletiva e diversa; evolução constante; apetite ao risco; movidos a desafios; e o B.O. é sempre nosso.'};
export const executiveSecretariats=[
  {id:'SETD',name:'SETD — Secretaria Executiva de Transformação Digital',short:'SETD'},
  {id:'SECTN',name:'SECTN — Secretaria Executiva de Ciência, Tecnologia e Novos Negócios',short:'SECTN'},
  {id:'SEIID',name:'SEIID — Secretaria Executiva de Inovação e Inclusão Digital',short:'SEIID'},
  {id:'GAB',name:'GAB — Gabinete do Secretário',short:'GAB'}
];
export const axes=[{id:'S',name:'S — Simplificar a relação com o cidadão'},{id:'P',name:'P — Promover as pessoas e a cidade'},{id:'C',name:'C — Cuidar das pessoas e da cidade'}];
export const objectives:Record<string,string[]>= {S:['Democratizar o acesso a serviços públicos digitais','Tornar o serviço público inteligente e integrado'],P:['Conectar as pessoas a oportunidades, desenvolvimento e autonomia','Tornar a cidade mais moderna, inteligente e atrativa'],C:['Ampliar o alcance e a eficiência do cuidado individual','Fomentar soluções para uma cidade segura, integrada, resiliente e sustentável']};
export const areas:Record<string,string[]>={'Democratizar o acesso a serviços públicos digitais':['Atendimento Hiperpersonalizado','Omnicanalidade (Integração de Canais)','Governo Proativo e de Precisão','Mensageria Inteligente','Linguagem Simples','Feedback Integrado e Interativo'],'Tornar o serviço público inteligente e integrado':['Estrutura de Building Blocks','Análise de Dados para Gestão','Automação e Inteligência Artificial'],'Conectar as pessoas a oportunidades, desenvolvimento e autonomia':['Educação e Qualificação Profissional','Ocupação Formal e Empreendedorismo','Inclusão e Letramento Digital'],'Tornar a cidade mais moderna, inteligente e atrativa':['Infraestrutura Moderna','Atração de Investimentos','Novas Oportunidades de Negócios'],'Ampliar o alcance e a eficiência do cuidado individual':['Saúde Digital e Preventiva','Assistência Social Integrada','Lazer e Turismo Inteligentes'],'Fomentar soluções para uma cidade segura, integrada, resiliente e sustentável':['Infraestrutura Segura e Resiliente','Manutenção Dinâmica e Integrada','Controle Urbano Inteligente']};
const fix=(s:unknown)=>String(s??'').replace(/figitais/gi,'digitais').replace(/gestrão/gi,'gestão').replace(/ominicanalidade/gi,'omnicanalidade').trim();const key=(s:string)=>fix(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const canonicalObjective=(s:unknown)=>Object.values(objectives).flat().find(x=>key(x)===key(fix(s)))||fix(s);const canonicalArea=(s:unknown)=>Object.values(areas).flat().find(x=>key(x)===key(fix(s)))||fix(s);
const divergence=(name:string)=>{const n=key(name);if(n==='cnh recife')return'A base principal enquadra em Ocupação Formal e Empreendedorismo; a planilha resumida aponta Educação e Qualificação Profissional.';if(n.includes('bora impactar'))return'O enquadramento estratégico precisa ser validado.';if(n.includes('viva + cidadania')||n.includes('viva mais cidadania'))return'Verificar se Viva + Cidadania e Viva Mais Cidadania Digital são o mesmo programa ou nomes relacionados.';if(['e-suas','sistema e-suas','suas digital'].includes(n))return'Possível nome relacionado a E-SUAS, Sistema E-SUAS e SUAS Digital; não fundir antes da validação.';if(n==='suas facil')return'Decidir se é projeto próprio ou iniciativa vinculada ao SUAS Digital.';return undefined};
const base=imported.records.filter(r=>r.sourceSheet==='BD PLANO SECTI');const summary=imported.records.filter(r=>r.sourceSheet==='Planilha1');
const fromBase=(r:(typeof base)[number]):Project=>{const v=Object.values(r.raw) as unknown[];const name=fix(v[7]);const d=divergence(name);return{id:`base-${r.sourceRow}`,name,executive:fix(v[8])||'Pendente',axis:fix(v[3]),objective:canonicalObjective(v[5]),area:canonicalArea(v[6]),secondaryArea:'',initiatives:fix(v[9])?fix(v[9]).split(/\n|;/).filter(Boolean):[],goal:fix(v[10]),actual2025:fix(v[11]),target2026:fix(v[12]),target2027:fix(v[13]),target2028:fix(v[14]),unit:'',indicator:fix(v[15]),metric:fix(v[16]),frequency:'',owner:fix(v[17]),notes:`Fonte: ${r.sourceFile} · ${r.sourceSheet} · linha ${r.sourceRow}`,status:'Pendente',provenance:d?'Divergência a validar':'Importada da base',divergence:d,updatedAt:imported.importedAt,updatedBy:'Importação oficial'}};
const mergeProject=(a:Project,b:Project):Project=>{const extras:string[]=[];if(b.goal&&a.goal&&key(b.goal)!==key(a.goal))extras.push(`Meta adicional importada: ${b.goal}`);if(b.indicator&&a.indicator&&key(b.indicator)!==key(a.indicator))extras.push(`Indicador operacional importado: ${b.indicator}${b.metric?` — ${b.metric}`:''}`);return{...a,initiatives:[...new Set([...a.initiatives,...b.initiatives])],goal:a.goal||b.goal,actual2025:a.actual2025||b.actual2025,target2026:a.target2026||b.target2026,target2027:a.target2027||b.target2027,target2028:a.target2028||b.target2028,indicator:a.indicator||b.indicator,metric:a.metric||b.metric,owner:a.owner||b.owner,notes:[a.notes,b.notes,...extras].filter(Boolean).join('\n')}};
const collected=new Map<string,Project>();for(const r of base){const p=fromBase(r);if(!p.name||['suas inteligente','voucher 99'].includes(key(p.name)))continue;const k=key(p.name);collected.set(k,collected.has(k)?mergeProject(collected.get(k)!,p):p)}for(const r of summary){const v=Object.values(r.raw) as unknown[];const name=fix(v[3]);if(!name||collected.has(key(name))||['suas inteligente','voucher 99'].includes(key(name)))continue;const d=divergence(name);collected.set(key(name),{id:`resumo-${r.sourceRow}`,name,executive:'Pendente',axis:'',objective:fix(v[1]),area:'',secondaryArea:'',initiatives:[],goal:'',actual2025:'',target2026:'',target2027:'',target2028:'',unit:'',indicator:'',metric:'',frequency:'',owner:'',notes:`Importado somente da visão resumida: ${r.sourceFile} · ${r.sourceSheet} · linha ${r.sourceRow}. Estratégia original: ${fix(v[2])}`,status:'Pendente',provenance:d?'Divergência a validar':'Importada da base',divergence:d,updatedAt:imported.importedAt,updatedBy:'Importação oficial'})}export const initialProjects=[...collected.values()];
export const indicatorCatalog:IndicatorSuggestion[]=imported.records.filter(r=>r.sourceSheet==='BD'&&r.sourceFile.includes('INDICADORES')).map(r=>{const v=Object.values(r.raw) as unknown[];return{subject:fix(v[0]),name:fix(v[1]),executive:fix(v[2]),type:fix(v[3]),unit:fix(v[5]),metric:fix(v[6]),frequency:fix(v[8]),direction:fix(v[9]),owner:fix(v[11]),sourceRow:r.sourceRow}}).filter(i=>i.name);
